export const card = [
    {
        place: 1,
        level: 1,
        color: 'purple',
        name: 'Кинотеатр',
        price: 50,
        rentPrice: 3,
        taxPrice: 3,
        expansionPrice: 50,
    },
    {
        place: 2,
        level: 2,
        color: 'purple',
        name: 'Казино',
        price: 60,
        rentPrice: 5,
        taxPrice: 3,
        expansionPrice: 50,
    },
    {
        place: 3,
        level: 3,
        color: 'purple',
        name: 'Ночной клуб',
        price: 70,
        rentPrice: 6,
        taxPrice: 3,
        expansionPrice: 50,
    },
    {
        place: 7,
        level: 1,
        color: 'red',
        name: 'Шоколадная фабрика',
        price: 90,
        rentPrice: 8,
        taxPrice: 5,
        expansionPrice: 50,
    },
    {
        place: 9,
        level: 2,
        color: 'red',
        name: 'Пивоваренный завод',
        price: 100,
        rentPrice: 10,
        taxPrice: 5,
        expansionPrice: 50,
    },
    {
        place: 11,
        level: 1,
        color: 'orange',
        name: 'Интернет-провайдер',
        price: 130,
        rentPrice: 14,
        taxPrice: 8,
        expansionPrice: 100,
    },
    {
        place: 12,
        level: 2,
        color: 'orange',
        name: 'Пейджинговая компания',
        price: 140,
        rentPrice: 18,
        taxPrice: 8,
        expansionPrice: 100,
    },
    {
        place: 13,
        level: 3,
        color: 'orange',
        name: 'Оператор сотовой связи',
        price: 150,
        rentPrice: 22,
        taxPrice: 8,
        expansionPrice: 100,
    },
    {
        place: 16,
        level: 1,
        color: 'yellow',
        name: 'Обувная фабрика',
        price: 170,
        rentPrice: 24,
        taxPrice: 12,
        expansionPrice: 100,
    },
    {
        place: 18,
        level: 2,
        color: 'yellow',
        name: 'Мебельное производство',
        price: 180,
        rentPrice: 26,
        taxPrice: 12,
        expansionPrice: 100,
    },
    {
        place: 19,
        level: 3,
        color: 'yellow',
        name: 'Швейное объединение',
        price: 190,
        rentPrice: 28,
        taxPrice: 12,
        expansionPrice: 100,
    },
    {
        place: 21,
        level: 1,
        color: 'green',
        name: 'Издательский дом',
        price: 210,
        rentPrice: 30,
        taxPrice: 15,
        expansionPrice: 150,
    },
    {
        place: 22,
        level: 2,
        color: 'green',
        name: 'Радиостанция',
        price: 220,
        rentPrice: 32,
        taxPrice: 15,
        expansionPrice: 150,
    },
    {
        place: 24,
        level: 3,
        color: 'green',
        name: 'Телевизионная компания',
        price: 230,
        rentPrice: 34,
        taxPrice: 15,
        expansionPrice: 150,
    },
    {
        place: 26,
        level: 1,
        color: 'sea',
        name: 'Железнодорожное предприятие',
        price: 250,
        rentPrice: 36,
        taxPrice: 20,
        expansionPrice: 150,
    },
    {
        place: 27,
        level: 2,
        color: 'sea',
        name: 'Морское пародство',
        price: 260,
        rentPrice: 38,
        taxPrice: 20,
        expansionPrice: 150,
    },
    {
        place: 29,
        level: 3,
        color: 'sea',
        name: 'Авиакомпания',
        price: 270,
        rentPrice: 40,
        taxPrice: 20,
        expansionPrice: 150,
    },
    {
        place: 31,
        level: 1,
        color: 'cyan',
        name: 'Автомобильный завод',
        price: 290,
        rentPrice: 42,
        taxPrice: 25,
        expansionPrice: 200,
    },
    {
        place: 33,
        level: 2,
        color: 'cyan',
        name: 'Судостроительный завод',
        price: 300,
        rentPrice: 46,
        taxPrice: 25,
        expansionPrice: 200,
    },
    {
        place: 34,
        level: 3,
        color: 'cyan',
        name: 'Металлургический комбинат',
        price: 310,
        rentPrice: 50,
        taxPrice: 25,
        expansionPrice: 200,
    },
    {
        place: 37,
        level: 1,
        color: 'blue',
        name: 'Угольный синдикат',
        price: 340,
        rentPrice: 54,
        taxPrice: 30,
        expansionPrice: 200,
    },
    {
        place: 39,
        level: 2,
        color: 'blue',
        name: 'Нефтяной холдинг',
        price: 350,
        rentPrice: 60,
        taxPrice: 30,
        expansionPrice: 200,
    },
];

export const centralCard = [
    {
        name: 'Самолет',
        price: '500',
    },
    {
        name: 'Яхта',
        price: '500',
    },
    {
        name: 'Поезд',
        price: '500',
    },
    {
        name: 'Автомобиль',
        price: '500',
    },
];
